import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'placehold.co', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'images.unsplash.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'picsum.photos', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i0.wp.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i1.wp.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i2.wp.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'hdhub4u.cologne', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'catimages.org', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'image.tmdb.org', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'imgshare.info', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.themoviedb.org', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'imagetot.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'myimg.click', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'secure.gravatar.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i.ibb.co', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i.imgur.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 's19.postimg.org', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'extraimage.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'keepimg.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.jiopic.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: '3.bp.blogspot.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: '4.bp.blogspot.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: '2.bp.blogspot.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'moscoop.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'extraimage.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i3.cloudimage.xyz', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'm.media-amazon.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: '1.bp.blogspot.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'pbs.twimg.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'media.themoviedb.org', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i5.cloudimage.xyz', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'assets.gadgets360cdn.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'malzo.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'img.7xflix.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i.ytimg.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i.im.ge', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'a.imge.to', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'hdhub4u.how', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i4.cloudimage.xyz', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'images.fandango.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'desiremovies.life', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i2.extraimage.info', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'occ-0-2186-2164.1.nflxso.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'api.vrott.tv', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'snoopimages.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'hdhub4u.gratis', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 's28.postimg.cc', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'tgraph.io', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'lookimg.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 's7.postimg.cc', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'imageflix.cam', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'extraimage.online', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.tvinsider.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'images.justwatch.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'extraimages.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i2.cinestaan.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'img1.imageride.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.bolly2tolly.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.gstatic.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'imgbbb.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.cinemapolitics.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'cdn-static.denofgeek.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'cb01.lat', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'pichub.site', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'image.ibb.co', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'theprimetime.in', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.iwmbuzz.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'contentmediasolution.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'movie24online.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'akamaividz2.zee5.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: '300mbmovieshub.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i.extraimages.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'tellypic.xyz', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'images2.static-bluray.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i.postimg.cc', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'hdhub4u.spa', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'tamilrockerss.co.in', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 's3.ap-south-1.amazonaws.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'img1.hotstarext.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.snoopimages.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.socialnews.xyz', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'img.indiaforums.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'v3img.voot.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'i.pinimg.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'etvbharatimages.akamaized.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 't0.blockdit.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'www.hindustantimes.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'qqcdnpictest.mxplay.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'english-films.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'bioskop1080.net', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'encrypted-tbn3.gstatic.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'latesthdmovies.cfd', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'is-1.mxplay.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'subtitri.do.am', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'encrypted-tbn1.gstatic.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'popcornreviewss.com', port: '', pathname: '/**' },
      { protocol: 'https', hostname: 'filmmusikdk.files.wordpress.com', port: '', pathname: '/**' },
    ],
  },
};

export default nextConfig;
